apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3-bucket.demo.kubecon.io
  labels:
    provider: aws
    service: s3
spec:
  compositeTypeRef:
    apiVersion: demo.kubecon.io/v1alpha1
    kind: XS3Bucket

  mode: Pipeline
  pipeline:
    - step: create-s3-bucket
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          # S3 Bucket
          - name: bucket
            base:
              apiVersion: s3.aws.upbound.io/v1beta1
              kind: Bucket
              spec:
                forProvider:
                  forceDestroy: true  # For demo purposes

            patches:
              # Patch bucket name with tenant-atlantis prefix
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      fmt: "tenant-atlantis-%s"
                      type: Format

              # Patch region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.region
                toFieldPath: spec.forProvider.region

              # Patch tags - merge with standard tags
              - type: FromCompositeFieldPath
                fromFieldPath: spec.tags
                toFieldPath: spec.forProvider.tags
                policy:
                  mergeOptions:
                    keepMapValues: true

              # Add standard tags
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.tags["gwcp:v1:tenant:app-name"]

              - type: ToCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: status.bucketName

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.arn
                toFieldPath: status.bucketArn

              - type: ToCompositeFieldPath
                fromFieldPath: spec.forProvider.region
                toFieldPath: status.region

            readinessChecks:
              - type: NonEmpty
                fieldPath: status.atProvider.arn

          # S3 Bucket Versioning
          - name: bucket-versioning
            base:
              apiVersion: s3.aws.upbound.io/v1beta2
              kind: BucketVersioning
              spec:
                forProvider:
                  versioningConfiguration:
                    status: Enabled

            patches:
              # Reference the bucket using bucketRef
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: spec.forProvider.bucketRef.name
                transforms:
                  - type: string
                    string:
                      fmt: "tenant-atlantis-%s"
                      type: Format

              # Patch region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.region
                toFieldPath: spec.forProvider.region

              # Enable versioning based on spec
              - type: FromCompositeFieldPath
                fromFieldPath: spec.versioning
                toFieldPath: spec.forProvider.versioningConfiguration.status
                transforms:
                  - type: convert
                    convert:
                      toType: string
                  - type: map
                    map:
                      "true": "Enabled"
                      "false": "Suspended"

          # S3 Bucket Public Access Block
          - name: bucket-public-access-block
            base:
              apiVersion: s3.aws.upbound.io/v1beta1
              kind: BucketPublicAccessBlock
              spec:
                forProvider:
                  blockPublicAcls: true
                  blockPublicPolicy: true
                  ignorePublicAcls: true
                  restrictPublicBuckets: true

            patches:
              # Reference the bucket
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: spec.forProvider.bucket
                transforms:
                  - type: string
                    string:
                      fmt: "tenant-atlantis-%s"
                      type: Format

              # Patch region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.region
                toFieldPath: spec.forProvider.region
