apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kratix-platform
  namespace: default
spec:
  description: |
    Kratix Promise Framework deployment showing platform abstraction
    for AWS DynamoDB resource provisioning

  components:
    # Deploy the Kratix DynamoDB Promise
    - name: dynamodb-promise
      type: kratix-promise-deployer
      description: "Deploy aws-dynamodb-kratix Promise to provide DynamoDB table abstraction"
      properties:
        version: "0.1.0"
        platform: "aws"
        service: "dynamodb"
        namespace: "kratix"
        workflowImage: "ghcr.io/syntasso/kratix-workflow:latest"
        api:
          apiVersion: "dynamodb.kratix.io/v1alpha1"
          kind: "DynamoDBRequest"
          metadata:
            name: "dynamodb-request"
          spec:
            schema:
              group: "dynamodb.kratix.io"
              kind: "DynamoDBRequest"
              names:
                kind: "DynamoDBRequest"
                plural: "dynamodbrequests"
                singular: "dynamodbrequest"
              scope: "Namespaced"
              version: "v1alpha1"
              # Schema properties for DynamoDB table requests
              properties:
                spec:
                  type: object
                  required:
                    - name
                    - region
                    - attributeDefinitions
                    - keySchema
                  properties:
                    name:
                      description: "Name of the DynamoDB table"
                      type: string
                      minLength: 3
                      maxLength: 255
                      pattern: '^[a-zA-Z0-9._-]+$'
                    region:
                      description: "AWS region where the table will be created"
                      type: string
                      enum:
                        - "us-east-1"
                        - "us-east-2"
                        - "us-west-1"
                        - "us-west-2"
                        - "eu-west-1"
                        - "eu-central-1"
                        - "ap-southeast-1"
                        - "ap-northeast-1"
                        - "ap-south-1"
                    billingMode:
                      description: "Billing mode for the table (PAY_PER_REQUEST or PROVISIONED)"
                      type: string
                      enum:
                        - "PAY_PER_REQUEST"
                        - "PROVISIONED"
                      default: "PAY_PER_REQUEST"
                    attributeDefinitions:
                      description: "Attributes defined for the table"
                      type: array
                      minItems: 1
                      items:
                        type: object
                        required:
                          - name
                          - type
                        properties:
                          name:
                            type: string
                            minLength: 1
                            maxLength: 255
                          type:
                            type: string
                            enum: ["S", "N", "B"]
                            description: "Attribute type (S=String, N=Number, B=Binary)"
                    keySchema:
                      description: "Primary key schema for the table"
                      type: array
                      minItems: 1
                      maxItems: 2
                      items:
                        type: object
                        required:
                          - attributeName
                          - keyType
                        properties:
                          attributeName:
                            type: string
                          keyType:
                            type: string
                            enum: ["HASH", "RANGE"]
                            description: "HASH for partition key, RANGE for sort key"
                    provisioned:
                      description: "Provisioned throughput configuration (only for PROVISIONED billing mode)"
                      type: object
                      properties:
                        readCapacity:
                          type: integer
                          minimum: 1
                          maximum: 40000
                        writeCapacity:
                          type: integer
                          minimum: 1
                          maximum: 40000

        # Deploy to the current cluster
        destinationSelectors:
          - matchLabels:
              cluster-role: "master"
