apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: dynamodbtable
spec:
  schema:
    apiVersion: v1alpha1
    kind: DynamoDBTable

    types:
      AttributeDefinition:
        attributeName: string
        attributeType: string

      KeySchemaElement:
        attributeName: string
        keyType: string

      Tag:
        key: string
        value: string

    spec:
      tableName: string
      region: string
      billingMode: "string | default=\"PAY_PER_REQUEST\""

      # Throughput (only for PROVISIONED mode)
      provisionedThroughput:
        readCapacityUnits: integer
        writeCapacityUnits: integer

      # Schema definition
      attributeDefinitions: "[]AttributeDefinition"
      keySchema: "[]KeySchemaElement"

      # Note: Global and local secondary indexes are not supported in this RGD
      # For complex table schemas with secondary indexes, use ACK Table directly

      # Features
      streamEnabled: "boolean | default=false"
      streamViewType: string
      sseEnabled: "boolean | default=false"
      sseType: string
      kmsMasterKeyID: string
      deletionProtectionEnabled: "boolean | default=false"
      tableClass: string

      # Note: pointInTimeRecoveryEnabled and ttlEnabled/ttlAttributeName are not supported
      # These require nested specifications that ACK doesn't expose in its simple Table schema
      # For TTL and PITR support, use ACK Table directly or manage via AWS API

      # Tags
      tags: "[]Tag"
    status:
      tableArn: ${table.status.ackResourceMetadata.arn}
      tableStatus: ${table.status.tableStatus}
      tableID: ${table.status.tableID}
      latestStreamArn: ${table.status.?latestStreamARN}
      itemCount: ${table.status.itemCount}
      tableSizeBytes: ${table.status.tableSizeBytes}
      creationDateTime: ${table.status.creationDateTime}
      conditions: ${table.status.conditions}

  resources:
    - id: table
      template:
        apiVersion: dynamodb.services.k8s.aws/v1alpha1
        kind: Table
        metadata:
          name: ${schema.spec.tableName}
          annotations:
            services.k8s.aws/region: ${schema.spec.region}
        spec:
          tableName: ${schema.spec.tableName}
          billingMode: ${schema.spec.billingMode}
          attributeDefinitions: ${schema.spec.attributeDefinitions}
          keySchema: ${schema.spec.keySchema}
