apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: session-api-app-xp
  namespace: default
spec:
  components:
    # Session Management API service (Crossplane version)
    # Note: DynamoDB table (api-sessions-xp) is pre-created by setup.sh Job
    - name: session-api-xp
      type: webservice
      properties:
        image: session-api:latest
        imagePullPolicy: IfNotPresent
        ports:
          - port: 8080
            expose: true
        env:
          - name: DYNAMODB_TABLE_NAME
            value: "api-sessions-xp"
          - name: AWS_REGION
            value: "us-west-2"
          - name: LOCALSTACK_ENDPOINT
            value: "http://localstack.localstack-system.svc.cluster.local:4566"
          - name: AWS_ACCESS_KEY_ID
            value: "test"
          - name: AWS_SECRET_ACCESS_KEY
            value: "test"
          - name: SESSION_TTL_HOURS
            value: "24"
          - name: PORT
            value: "8080"
          - name: FLASK_ENV
            value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
