apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: dynamodb-production-example
  namespace: default
spec:
  components:
    - name: user-table
      type: aws-dynamodb-kro
      properties:
        tableName: users-table-production
        region: us-east-1
        billingMode: PAY_PER_REQUEST

        # Define attributes used in keys or indexes
        attributeDefinitions:
          - attributeName: userId
            attributeType: "S"
          - attributeName: email
            attributeType: "S"
          - attributeName: createdAt
            attributeType: "N"

        # Primary key schema (partition key + sort key)
        keySchema:
          - attributeName: userId
            keyType: HASH
          - attributeName: createdAt
            keyType: RANGE

        # Global Secondary Index for querying by email
        globalSecondaryIndexes:
          - indexName: email-index
            keySchema:
              - attributeName: email
                keyType: HASH
            projection:
              projectionType: ALL

        # Enable streams for change data capture
        streamEnabled: true
        streamViewType: NEW_AND_OLD_IMAGES

        # Enable point-in-time recovery for backups
        pointInTimeRecoveryEnabled: true

        # Enable server-side encryption with AWS managed key
        sseEnabled: true
        sseType: AES256

        # Enable TTL for automatic expiration
        ttlEnabled: true
        ttlAttributeName: expiresAt

        # Enable deletion protection
        deletionProtectionEnabled: true

        # Add resource tags
        tags:
          - key: Environment
            value: Production
          - key: Application
            value: UserManagement
          - key: ManagedBy
            value: KubeVela

        # Use custom provider configuration
        providerConfigRef:
          name: aws-prod-provider

        # Write connection details to secret
        writeConnectionSecretToRef:
          name: user-table-connection
          namespace: default
