apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: dynamodb-with-gsi-example
  namespace: default
spec:
  components:
    - name: user-table
      type: aws-dynamodb-kro
      properties:
        tableName: tenant-atlantis-users-table-with-gsi
        region: us-west-2
        billingMode: PAY_PER_REQUEST

        # Define attributes used in keys or indexes
        attributeDefinitions:
          - attributeName: userId
            attributeType: "S"
          - attributeName: email
            attributeType: "S"

        # Primary key schema (partition key only)
        keySchema:
          - attributeName: userId
            keyType: HASH

        # Global Secondary Index for querying by email
        globalSecondaryIndexes:
          - indexName: email-index
            keySchema:
              - attributeName: email
                keyType: HASH
            projection:
              projectionType: ALL
