apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: dynamodb-production-with-traits
  namespace: default
spec:
  components:
    - name: orders-table
      type: aws-dynamodb-kro
      properties:
        tableName: orders-prod
        region: us-west-2

        # Table schema
        attributeDefinitions:
          - attributeName: orderId
            attributeType: "S"
          - attributeName: customerId
            attributeType: "S"
          - attributeName: orderDate
            attributeType: "N"

        keySchema:
          - attributeName: orderId
            keyType: HASH

        # Global secondary index for customer queries
        globalSecondaryIndexes:
          - indexName: customer-index
            keySchema:
              - attributeName: customerId
                keyType: HASH
              - attributeName: orderDate
                keyType: RANGE
            projection:
              projectionType: ALL

        # Tags
        tags:
          - key: Environment
            value: Production
          - key: Application
            value: OrderManagement

      # Apply production-grade traits
      traits:
        # Fixed capacity with auto-scaling (configured separately)
        - type: dynamodb-provisioned-capacity-kro
          properties:
            readCapacityUnits: 100
            writeCapacityUnits: 50

        # Full data protection
        - type: dynamodb-protection-kro
          properties:
            deletionProtection: true
            pointInTimeRecovery: true

        # Customer-managed encryption
        - type: dynamodb-encryption-kro
          properties:
            sseType: KMS
            kmsKeyId: alias/orders-prod-key

        # Change data capture for analytics
        - type: dynamodb-streams-kro
          properties:
            viewType: NEW_AND_OLD_IMAGES
