# DynamoDB table with deletion protection and point-in-time recovery
# Essential for production environments
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: protected-table
  namespace: production
spec:
  components:
    - name: critical-data-table
      type: aws-dynamodb-xp
      properties:
        region: us-east-1
        attributeDefinitions:
          - attributeName: dataId
            attributeType: "S"
        keySchema:
          - attributeName: dataId
            keyType: HASH
        tags:
          - key: Environment
            value: Production
          - key: CriticalData
            value: "true"
      traits:
        - type: dynamodb-protection-xp
          properties:
            deletionProtection: true
            pointInTimeRecovery: true
