# DynamoDB table with composite key (partition + sort key)
# Useful for time-series data or hierarchical data
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: user-events
  namespace: default
spec:
  components:
    - name: events-table
      type: aws-dynamodb-xp
      properties:
        region: us-west-2
        attributeDefinitions:
          - attributeName: userId
            attributeType: "S"
          - attributeName: timestamp
            attributeType: "N"
        keySchema:
          - attributeName: userId
            keyType: HASH
          - attributeName: timestamp
            keyType: RANGE
        tags:
          - key: Application
            value: Analytics
          - key: Environment
            value: Development
