apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: dynamodbtable
spec:
  schema:
    apiVersion: v1alpha1
    kind: DynamoDBTable

    types:
      AttributeDefinition:
        attributeName: string
        attributeType: string

      KeySchemaElement:
        attributeName: string
        keyType: string

      Tag:
        key: string
        value: string

    spec:
      tableName: string
      region: string
      billingMode: "string | default=\"PAY_PER_REQUEST\""

      # Schema definition
      attributeDefinitions: "[]AttributeDefinition"
      keySchema: "[]KeySchemaElement"

      # ⚠️ ORPHANED PROPERTIES (not mapped to ACK Table - silently ignored)
      # These properties are defined in this RGD schema but are NOT mapped in the
      # resources template (lines 74-78). KRO will silently ignore any values you provide.
      # To use these features, either:
      # 1. Add template mappings below (for supported ACK fields)
      # 2. Use ACK Table custom resource directly (for unsupported fields)
      # 3. Manage via AWS API after table creation
      #
      # Potentially mappable to ACK (if added to template):
      # - provisionedThroughput (for PROVISIONED billing mode)
      # - streamEnabled, streamViewType
      # - sseEnabled, sseType, kmsMasterKeyID
      # - deletionProtectionEnabled
      # - tableClass
      # - tags
      #
      # Not supported by ACK's simple Table API:
      # - Global and local secondary indexes (use ACK GlobalSecondaryIndexes field)
      # - pointInTimeRecoveryEnabled (use ACK PointInTimeRecoverySpecification)
      # - ttlEnabled/ttlAttributeName (use ACK TTL field after table creation)
    status:
      tableArn: ${table.status.ackResourceMetadata.arn}
      tableStatus: ${table.status.tableStatus}
      tableID: ${table.status.tableID}
      latestStreamArn: ${table.status.?latestStreamARN}
      itemCount: ${table.status.itemCount}
      tableSizeBytes: ${table.status.tableSizeBytes}
      creationDateTime: ${table.status.creationDateTime}
      conditions: ${table.status.conditions}

  resources:
    - id: table
      template:
        apiVersion: dynamodb.services.k8s.aws/v1alpha1
        kind: Table
        metadata:
          name: ${schema.spec.tableName}
          annotations:
            services.k8s.aws/region: ${schema.spec.region}
        spec:
          tableName: ${schema.spec.tableName}
          billingMode: ${schema.spec.billingMode}
          attributeDefinitions: ${schema.spec.attributeDefinitions}
          keySchema: ${schema.spec.keySchema}
