apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dynamodb-table.demo.kubecon.io
spec:
  compositeTypeRef:
    apiVersion: demo.kubecon.io/v1alpha1
    kind: XDynamoDBTable

  mode: Pipeline
  pipeline:
    - step: create-table
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: table
            base:
              apiVersion: dynamodb.aws.upbound.io/v1beta1
              kind: Table
              spec:
                forProvider:
                  billingMode: PAY_PER_REQUEST

            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: metadata.name

              - type: FromCompositeFieldPath
                fromFieldPath: spec.region
                toFieldPath: spec.forProvider.region

              - type: FromCompositeFieldPath
                fromFieldPath: spec.hashKey
                toFieldPath: spec.forProvider.hashKey

              - type: FromCompositeFieldPath
                fromFieldPath: spec.attributes
                toFieldPath: spec.forProvider.attribute

              - type: FromCompositeFieldPath
                fromFieldPath: spec.tags
                toFieldPath: spec.forProvider.tags

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.arn
                toFieldPath: status.tableArn

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.tableId
