apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: webservice-s3-demo
  namespace: default
spec:
  components:
    - name: demo-s3-bucket
      type: s3-bucket
      properties:
        region: us-west-2
        bucketName: webservice-demo-bkane-2
      traits:
        - type: s3-encryption
          properties:
            algorithm: AES256
        - type: s3-public-access-block
          properties:
            blockPublicAcls: true
            blockPublicPolicy: true
            ignorePublicAcls: true
            restrictPublicBuckets: true
        - type: s3-tags
          properties:
            tags:
              Environment: demo
              Component: s3-storage
              App: webservice-s3-demo
    
    - name: welcome-file
      type: s3-object
      properties:
        bucket: "PLACEHOLDER_BUCKET_NAME"
        key: "welcome.txt"
        content: |
          Welcome to KubeCon 2025 S3 Demo!
          
          This file was created using KubeVela and Crossplane.
          You're viewing this through our custom S3 browser web app.
          
          Tools used:
          - KubeVela for application orchestration
          - Crossplane for S3 infrastructure
          - Python Flask for the web interface
          
          Enjoy exploring the bucket contents!
        contentType: "text/plain"

    - name: demo-data
      type: s3-object
      properties:
        bucket: "PLACEHOLDER_BUCKET_NAME"
        key: "demo-data.json"
        content: |
          {
            "event": "KubeCon 2025",
            "demo": "S3 Browser with Live Content",
            "created_by": "KubeVela + Crossplane",
            "bucket_contents": [
              "welcome.txt",
              "demo-data.json",
              "README.md"
            ],
            "technologies": {
              "orchestration": "KubeVela",
              "infrastructure": "Crossplane", 
              "runtime": "Kubernetes",
              "web_framework": "Python Flask",
              "cloud_storage": "AWS S3"
            }
          }
        contentType: "application/json"

    - name: readme-file
      type: s3-object
      properties:
        bucket: "PLACEHOLDER_BUCKET_NAME"
        key: "README.md"
        content: |
          # KubeCon 2025 S3 Demo
          
          ## Overview
          This demonstration shows how to use **KubeVela** and **Crossplane** together to:
          
          1. 🪣 **Create S3 buckets** declaratively
          2. 📁 **Populate with content** using Infrastructure as Code  
          3. 🌐 **Build web applications** that interact with the infrastructure
          4. 🔄 **Orchestrate dependencies** with workflows
          
          ## Architecture
          - **KubeVela Application** orchestrates the entire stack
          - **Crossplane** manages AWS S3 resources
          - **Python Flask app** provides the web interface
          - **Workflow** ensures proper creation order
          
          ## Live Demo
          You're currently viewing this through our custom S3 browser!
          
          ---
          *Infrastructure as Code in action* ⚡
        contentType: "text/plain"
    
    - name: demo-webservice
      type: webservice
      properties:
        image: python:3.9-slim
        ports:
          - port: 5000
            expose: true
        cmd:
          - "sh"
          - "-c"
          - |
            pip install flask boto3 && cat > app.py << 'EOF'
            import os
            import boto3
            from flask import Flask, render_template_string
            from botocore.exceptions import ClientError, NoCredentialsError

            app = Flask(__name__)

            LIST_TEMPLATE = '''
            <!DOCTYPE html>
            <html>
            <head>
                <title>S3 Bucket Browser</title>
                <style>
                    body { font-family: Arial, sans-serif; margin: 20px; background-color: #f8f9fa; }
                    .container { max-width: 1000px; margin: 0 auto; }
                    .bucket-info { background-color: #e3f2fd; padding: 15px; margin-bottom: 20px; border-radius: 8px; border: 1px solid #2196f3; }
                    .object { border: 1px solid #ddd; padding: 15px; margin: 10px 0; background: white; border-radius: 5px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                    .object-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; }
                    .object-name { font-weight: bold; font-size: 1.1em; color: #1976d2; }
                    .object-meta { color: #666; font-size: 0.9em; }
                    .view-button { background-color: #4caf50; color: white; padding: 8px 16px; text-decoration: none; border-radius: 4px; font-size: 0.9em; }
                    .view-button:hover { background-color: #45a049; }
                    .error { color: red; background-color: #ffebee; padding: 15px; border-radius: 5px; border: 1px solid #f44336; }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>🪣 S3 Bucket Browser</h1>
                    <div class="bucket-info">
                        <h3>📋 Bucket Information</h3>
                        <p><strong>Bucket Name:</strong> {{ bucket_name }}</p>
                        <p><strong>Bucket ARN:</strong> {{ bucket_arn }}</p>
                        <p><strong>Region:</strong> {{ region }}</p>
                    </div>
                    
                    {% if error %}
                        <div class="error">
                            <h3>❌ Error</h3>
                            <p>{{ error }}</p>
                        </div>
                    {% else %}
                        <h3>📁 Bucket Contents ({{ object_count }} objects)</h3>
                        {% for obj in objects %}
                            <div class="object">
                                <div class="object-header">
                                    <div>
                                        <div class="object-name">📄 {{ obj.key }}</div>
                                        <div class="object-meta">Size: {{ obj.size }} bytes | Modified: {{ obj.last_modified }}</div>
                                    </div>
                                    <a href="/view/{{ obj.key }}" class="view-button">👀 View Content</a>
                                </div>
                            </div>
                        {% endfor %}
                        {% if object_count == 0 %}
                            <p><em>Bucket is empty - files may still be uploading...</em></p>
                        {% endif %}
                    {% endif %}
                </div>
            </body>
            </html>
            '''

            FILE_TEMPLATE = '''
            <!DOCTYPE html>
            <html>
            <head>
                <title>{{ filename }} - S3 File Viewer</title>
                <style>
                    body { font-family: Arial, sans-serif; margin: 20px; background-color: #f8f9fa; }
                    .container { max-width: 1000px; margin: 0 auto; }
                    .nav { margin-bottom: 20px; padding: 10px; background: white; border-radius: 5px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                    .nav a { color: #1976d2; text-decoration: none; margin-right: 20px; }
                    .nav a:hover { text-decoration: underline; }
                    .file-info { background-color: #e8f5e8; padding: 15px; margin-bottom: 20px; border-radius: 8px; border: 1px solid #4caf50; }
                    .content-box { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                    .content { white-space: pre-wrap; font-family: 'Courier New', monospace; line-height: 1.5; }
                    .json-content { background-color: #f5f5f5; padding: 15px; border-radius: 5px; }
                    .error { color: red; background-color: #ffebee; padding: 15px; border-radius: 5px; border: 1px solid #f44336; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="nav">
                        <a href="/">🏠 Back to Bucket</a>
                        <span>📄 Viewing: <strong>{{ filename }}</strong></span>
                    </div>
                    
                    {% if error %}
                        <div class="error">
                            <h3>❌ Error</h3>
                            <p>{{ error }}</p>
                        </div>
                    {% else %}
                        <div class="file-info">
                            <h3>📋 File Information</h3>
                            <p><strong>File:</strong> {{ filename }}</p>
                            <p><strong>Size:</strong> {{ size }} bytes</p>
                            <p><strong>Content Type:</strong> {{ content_type }}</p>
                            <p><strong>Last Modified:</strong> {{ last_modified }}</p>
                        </div>
                        
                        <div class="content-box">
                            <h3>📖 File Contents</h3>
                            <div class="content {{ 'json-content' if content_type == 'application/json' }}">{{ content }}</div>
                        </div>
                    {% endif %}
                </div>
            </body>
            </html>
            '''

            @app.route('/')
            def index():
                bucket_name = os.getenv('S3_BUCKET_NAME', 'unknown')
                bucket_arn = os.getenv('S3_BUCKET_ARN', 'unknown') 
                region = os.getenv('AWS_DEFAULT_REGION', 'unknown')
                
                try:
                    s3 = boto3.client('s3', region_name=region)
                    response = s3.list_objects_v2(Bucket=bucket_name)
                    
                    objects = []
                    if 'Contents' in response:
                        for obj in response['Contents']:
                            objects.append({
                                'key': obj['Key'],
                                'size': obj['Size'],
                                'last_modified': obj['LastModified'].strftime('%Y-%m-%d %H:%M:%S')
                            })
                    
                    return render_template_string(LIST_TEMPLATE, 
                                                bucket_name=bucket_name,
                                                bucket_arn=bucket_arn,
                                                region=region,
                                                objects=objects,
                                                object_count=len(objects),
                                                error=None)
                                                
                except NoCredentialsError:
                    return render_template_string(LIST_TEMPLATE,
                                                bucket_name=bucket_name,
                                                bucket_arn=bucket_arn, 
                                                region=region,
                                                objects=[],
                                                object_count=0,
                                                error="AWS credentials not found")
                except ClientError as e:
                    return render_template_string(LIST_TEMPLATE,
                                                bucket_name=bucket_name,
                                                bucket_arn=bucket_arn,
                                                region=region, 
                                                objects=[],
                                                object_count=0,
                                                error=f"AWS Error: {e}")
                except Exception as e:
                    return render_template_string(LIST_TEMPLATE,
                                                bucket_name=bucket_name,
                                                bucket_arn=bucket_arn,
                                                region=region,
                                                objects=[],
                                                object_count=0,
                                                error=f"Unexpected error: {e}")

            @app.route('/view/<path:filename>')
            def view_file(filename):
                bucket_name = os.getenv('S3_BUCKET_NAME', 'unknown')
                region = os.getenv('AWS_DEFAULT_REGION', 'unknown')
                
                try:
                    s3 = boto3.client('s3', region_name=region)
                    
                    # Get object metadata
                    head_response = s3.head_object(Bucket=bucket_name, Key=filename)
                    
                    # Get object content
                    obj_response = s3.get_object(Bucket=bucket_name, Key=filename)
                    content = obj_response['Body'].read()
                    
                    # Try to decode as UTF-8, fallback to binary representation
                    try:
                        content_str = content.decode('utf-8')
                    except UnicodeDecodeError:
                        content_str = f"[Binary file - {len(content)} bytes]"
                    
                    return render_template_string(FILE_TEMPLATE,
                                                filename=filename,
                                                size=head_response.get('ContentLength', len(content)),
                                                content_type=head_response.get('ContentType', 'unknown'),
                                                last_modified=head_response.get('LastModified', 'unknown'),
                                                content=content_str,
                                                error=None)
                                                
                except NoCredentialsError:
                    return render_template_string(FILE_TEMPLATE,
                                                filename=filename,
                                                size=0,
                                                content_type="unknown",
                                                last_modified="unknown",
                                                content="",
                                                error="AWS credentials not found")
                except ClientError as e:
                    return render_template_string(FILE_TEMPLATE,
                                                filename=filename,
                                                size=0,
                                                content_type="unknown", 
                                                last_modified="unknown",
                                                content="",
                                                error=f"AWS Error: {e}")
                except Exception as e:
                    return render_template_string(FILE_TEMPLATE,
                                                filename=filename,
                                                size=0,
                                                content_type="unknown",
                                                last_modified="unknown", 
                                                content="",
                                                error=f"Unexpected error: {e}")

            if __name__ == '__main__':
                app.run(host='0.0.0.0', port=5000)
            EOF
            python app.py
        env:
          - name: S3_BUCKET_ARN
            value: "PLACEHOLDER_ARN"
          - name: S3_BUCKET_NAME
            value: "PLACEHOLDER_BUCKET_NAME"
          - name: AWS_DEFAULT_REGION
            value: "PLACEHOLDER_REGION"
          - name: AWS_REGION
            value: "PLACEHOLDER_REGION"
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: "/aws/creds"
        volumeMounts:
          secret:
            - name: aws-creds-vol
              mountPath: /aws
              secretName: aws-creds
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      traits:
        - type: scaler
          properties:
            replicas: 2
        - type: labels
          properties:
            app: webservice-s3-demo
            component: webservice
        - type: annotations
          properties:
            "app.kubernetes.io/name": webservice-s3-demo
            "app.kubernetes.io/component": webservice
  
  workflow:
    steps:
      - name: create-s3-bucket
        type: apply-component
        properties:
          component: demo-s3-bucket
        outputs:
          - name: bucket-arn
            valueFrom: output.status.atProvider.arn
          - name: bucket-id
            valueFrom: output.status.atProvider.id
          - name: bucket-region
            valueFrom: output.status.atProvider.region
      - name: create-welcome-file
        type: apply-component
        dependsOn: ["create-s3-bucket"]
        properties:
          component: welcome-file
        inputs:
          - from: bucket-id
            parameterKey: bucket
          - from: bucket-region
            parameterKey: region
      
      - name: create-demo-data
        type: apply-component
        dependsOn: ["create-s3-bucket"]
        properties:
          component: demo-data
        inputs:
          - from: bucket-id
            parameterKey: bucket
          - from: bucket-region
            parameterKey: region

      - name: create-readme-file
        type: apply-component
        dependsOn: ["create-s3-bucket"]
        properties:
          component: readme-file
        inputs:
          - from: bucket-id
            parameterKey: bucket
          - from: bucket-region
            parameterKey: region

      - name: create-webservice
        type: apply-component
        dependsOn: ["create-s3-bucket"]
        properties:
          component: demo-webservice
        inputs:
          - from: bucket-arn
            parameterKey: env[0].value
          - from: bucket-id
            parameterKey: env[1].value
          - from: bucket-region
            parameterKey: env[2].value
          - from: bucket-region
            parameterKey: env[3].value