apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: aws-dynamodb-kratix
  namespace: kratix-platform-system
spec:
  api:
    apiVersion: dynamodb.kratix.io/v1alpha1
    kind: DynamoDBRequest
    metadata:
      name: dynamodb-request
    spec:
      schema:
        group: dynamodb.kratix.io
        kind: DynamoDBRequest
        names:
          kind: DynamoDBRequest
          plural: dynamodbrequests
          singular: dynamodbrequest
        scope: Namespaced
        version: v1alpha1
        spec:
          type: object
          properties:
            name:
              description: "Name of the DynamoDB table"
              type: string
              minLength: 3
              maxLength: 255
            region:
              description: "AWS region"
              type: string
              default: "us-west-2"
            billingMode:
              description: "Billing mode"
              type: string
              enum:
                - PAY_PER_REQUEST
                - PROVISIONED
              default: PAY_PER_REQUEST
            attributeDefinitions:
              description: "Table attributes"
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                    enum:
                      - S
                      - N
                      - B
            keySchema:
              description: "Key schema"
              type: array
              items:
                type: object
                properties:
                  attributeName:
                    type: string
                  keyType:
                    type: string
                    enum:
                      - HASH
                      - RANGE
          required:
            - name
            - region

  # No workflows - just the API definition for now
  # This allows the promise to be deployed and users can create requests
  destinationSelectors:
    - matchLabels:
        kratix.io/enabled: "true"
