apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: aws-dynamodb-kratix
  namespace: kratix-platform-system
  labels:
    kratix.io/promise-version: "0.1.0"
    platform: aws
    service: dynamodb
spec:
  # API defines the CRD that users request when creating a DynamoDB table
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: dynamodbrequests.dynamodb.kratix.io
    spec:
      group: dynamodb.kratix.io
      scope: Namespaced
      names:
        kind: DynamoDBRequest
        plural: dynamodbrequests
        singular: dynamodbrequest
        listKind: DynamoDBRequestList
      versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    name:
                      description: "Name of the DynamoDB table"
                      type: string
                      minLength: 3
                      maxLength: 255
                    region:
                      description: "AWS region"
                      type: string
                      default: "us-west-2"
                      enum:
                        - us-east-1
                        - us-east-2
                        - us-west-1
                        - us-west-2
                        - eu-west-1
                        - eu-central-1
                        - ap-southeast-1
                        - ap-northeast-1
                        - ap-south-1
                    billingMode:
                      description: "Billing mode"
                      type: string
                      enum:
                        - PAY_PER_REQUEST
                        - PROVISIONED
                      default: PAY_PER_REQUEST
                    attributeDefinitions:
                      description: "Table attributes"
                      type: array
                      minItems: 1
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          type:
                            type: string
                            enum:
                              - "S"
                              - "N"
                              - "B"
                    keySchema:
                      description: "Key schema"
                      type: array
                      minItems: 1
                      items:
                        type: object
                        properties:
                          attributeName:
                            type: string
                          keyType:
                            type: string
                            enum:
                              - HASH
                              - RANGE
                    provisioned:
                      description: "Provisioned throughput (for PROVISIONED mode)"
                      type: object
                      properties:
                        readCapacity:
                          type: integer
                          minimum: 1
                          maximum: 40000
                          default: 5
                        writeCapacity:
                          type: integer
                          minimum: 1
                          maximum: 40000
                          default: 5
                  required:
                    - name
                    - region
                    - attributeDefinitions
                    - keySchema
                status:
                  type: object
                  properties:
                    tableStatus:
                      type: string
                    tableArn:
                      type: string
                    itemCount:
                      type: integer

  # Workflows define how Kratix processes requests
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: dynamodb-configure-pipeline
          spec:
            containers:
              - image: k3d-kubevela-registry:5000/kratix/dynamodb-resource-configure:0.1.0
                name: generate-table-manifest
                env:
                  - name: REQUEST_PATH
                    value: /kratix/input/object.yaml
                  - name: OUTPUT_STATE_PATH
                    value: /kratix/output
      delete:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: dynamodb-delete-pipeline
          spec:
            containers:
              - image: bitnami/kubectl:latest
                name: cleanup-dynamodb-table
                command:
                  - /bin/sh
                  - -c
                  - |
                    kubectl delete table \
                      -l kratix.io/request=$(cat /kratix/input/metadata.name) \
                      --namespace default 2>/dev/null || true

  # Destination selectors - deploy to the current cluster
  destinationSelectors:
    - matchLabels:
        kratix.io/enabled: "true"
