apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: aws-dynamodb-kratix
  namespace: kratix
  labels:
    kratix.io/promise-version: "0.1.0"
    platform: aws
    service: dynamodb

spec:
  # API defines the CRD that users request when creating a DynamoDB table
  api:
    apiVersion: dynamodb.kratix.io/v1alpha1
    kind: DynamoDBRequest
    metadata:
      name: dynamodb-request
    spec:
      schema:
        group: dynamodb.kratix.io
        kind: DynamoDBRequest
        names:
          kind: DynamoDBRequest
          plural: dynamodbrequests
          singular: dynamodbrequest
        scope: Namespaced
        version: v1alpha1
        spec:
          properties:
            name:
              description: "Name of the DynamoDB table"
              type: string
            region:
              description: "AWS region where the table will be created"
              type: string
              default: "us-west-2"
            billingMode:
              description: "Billing mode for the table"
              type: string
              default: "PAY_PER_REQUEST"
              enum:
                - "PAY_PER_REQUEST"
                - "PROVISIONED"
            attributeDefinitions:
              description: "Attributes for the table"
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: string
                    enum:
                      - "S"
                      - "N"
                      - "B"
            keySchema:
              description: "Key schema for the table"
              type: array
              items:
                type: object
                properties:
                  attributeName:
                    type: string
                  keyType:
                    type: string
                    enum:
                      - "HASH"
                      - "RANGE"

  # Destination selectors - deploy to the current cluster
  destinationSelectors:
    - matchLabels: {}
