apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: install
  namespace: vela-system
spec:
  workflowSpec:
    steps:
    - name: enable-kube-trigger
      type: addon-operation
      properties:
        addonName: kube-trigger
        operation: enable

    - name: enable-velaux
      type: addon-operation
      properties:
        addonName: velaux
        operation: enable

    - name: enable-fluxcd
      type: addon-operation
      properties:
        addonName: fluxcd
        operation: enable

    - name: wait-for-fluxcd
      type: wait-deployment
      dependsOn:
      - enable-fluxcd
      properties:
        name: fluxcd-helm-controller
        namespace: flux-system
        replicas: 1
        timeout: 300

    - name: enable-crossplane
      type: addon-operation
      dependsOn:
      - wait-for-fluxcd
      properties:
        addonName: crossplane
        operation: enable

    - name: wait-for-crossplane
      type: wait-deployment
      dependsOn:
      - enable-crossplane
      properties:
        name: crossplane
        namespace: crossplane-system
        replicas: 1
        timeout: 300

    - name: enable-crossplane-aws
      type: addon-operation
      dependsOn:
      - wait-for-crossplane
      properties:
        addonName: crossplane-aws
        operation: enable

    - name: enable-tenant-addon
      type: addon-operation
      dependsOn:
      - wait-for-crossplane
      properties:
        addonName: tenant
        operation: enable