apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: simpledynamodb-localstack
spec:
  schema:
    apiVersion: v1alpha1
    kind: SimpleDynamoDBLocalStack
    spec:
      # Table name: alphanumeric, hyphens, underscores, dots only (prevents shell injection)
      # Length: 3-255 characters (AWS DynamoDB rules)
      tableName: string & =~"^[a-zA-Z0-9._-]{3,255}$"

      # AWS region: standard format (e.g., us-west-2, eu-central-1)
      region: string & =~"^[a-z]{2}-[a-z]+-[0-9]{1}$"
    status:
      tableState: string

  resources:
    - id: dynamodbTable
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: dynamodb-table-${schema.spec.tableName}
          annotations:
            localstack/table-name: ${schema.spec.tableName}
            localstack/region: ${schema.spec.region}
        data:
          table-name: ${schema.spec.tableName}
          region: ${schema.spec.region}
          creation-script: |
            #!/bin/bash
            aws dynamodb create-table \
              --table-name ${schema.spec.tableName} \
              --attribute-definitions AttributeName=id,AttributeType=S \
              --key-schema AttributeName=id,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST \
              --endpoint-url http://localstack.localstack-system.svc.cluster.local:4566 \
              --region ${schema.spec.region}

    - id: tableCreatorJob
      template:
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: create-${schema.spec.tableName}
        spec:
          ttlSecondsAfterFinished: 3600
          template:
            spec:
              containers:
              - name: aws-cli
                image: amazon/aws-cli:2.15.17
                securityContext:
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
                  runAsUser: 1000
                  capabilities:
                    drop:
                      - ALL
                env:
                - name: AWS_ACCESS_KEY_ID
                  value: "test"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "test"
                - name: AWS_DEFAULT_REGION
                  value: ${schema.spec.region}
                command:
                - /bin/sh
                - -c
                - |
                  aws dynamodb create-table \
                    --table-name ${schema.spec.tableName} \
                    --attribute-definitions AttributeName=id,AttributeType=S \
                    --key-schema AttributeName=id,KeyType=HASH \
                    --billing-mode PAY_PER_REQUEST \
                    --endpoint-url http://localstack.localstack-system.svc.cluster.local:4566 \
                    --region ${schema.spec.region} && \
                  echo "Table created successfully" || \
                  (aws dynamodb describe-table --table-name ${schema.spec.tableName} \
                    --endpoint-url http://localstack.localstack-system.svc.cluster.local:4566 \
                    --region ${schema.spec.region} && echo "Table already exists")
              restartPolicy: Never
          backoffLimit: 3
